fn_params_layout = "compressed"
# fn_single_line = false
# group_imports = "StdExternalCrate"
short_array_element_width_threshold = 60
single_line_if_else_max_width = 70
single_line_let_else_max_width = 70
# struct_lit_single_line = true
struct_lit_width = 70
max_width = 120
chain_width = 80
